### ISSUE TITLE
App is not serving

### ISSUE THREAD

**Issue by bigboytr** [alsofronie/lumen-vue#2]
Thanks for the repo.
After `composer update` and `npm install` commands local server not showing on the browser.
I'm using xampp server. It's up and running.
I'm using `npm run watch` to run project. But blank page is appear on browser. I thing laravel-mix need a configuration but what ?
Could you please help ?

**Comment by alsofronie** [comment]
Hi. Although I never ran it in xampp (and I cannot recreate your env), it should still work. A blank page can be from xampp (but from what I can remember, xampp will provide an error response) or from the Vue subsystem if it has problems.

You should inspect the errors / warnings / messages from the browser `Console`. Paste them here if it's unclear, maybe I can help.

**Comment by bigboytr** [comment]
Hi, again. There are errors in console. They all not found error.
![image](https://user-images.githubusercontent.com/6952982/58072456-6920f300-7ba8-11e9-932a-634b4919f62a.png)

My project url is : http://localhost/lumen-vue and as you know that project runing on public folder.

**Comment by alsofronie** [comment]
It is clear that your setup is serving the content from a sub-directory (named `lumen-vue`) whereas all the paths injected from laravel-mix are pointing to the root folder. You may try a solution like the one described [here](https://laravel-news.com/subfolder-install) but I don't know if it will work in your case. Better yet, follow [this issue on Laravel mix](https://github.com/JeffreyWay/laravel-mix/issues/1026) maybe it can help you.
